export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';
export const TOGGLE_DELETE_ASIDE = 'TOGGLE_DELETE_ASIDE';
export const USER_SELECTED = 'USER_SELECTED';
