export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';
export const TOGGLE_REPLY = 'TOGGLE_REPLY';
export const TOGGLE_EDIT = 'TOOGLE_EDIT';
